"""Decides which files are the user's own work. Owner: Track A.

Excludes: dependency dirs (node_modules, vendor, venv), generated code and
scaffolding, build output, lock and minified files, and forks with no original
commits. Returns kept paths PLUS the exclusion list -- the exclusions are shown
in the UI for explainability, so do not throw them away.
"""

from pathlib import Path

EXCLUDED_DIRS = {
    "node_modules", "vendor", "venv", ".venv", "env", "site-packages",
    "dist", "build", "out", "target", ".next", "__pycache__", ".git",
    "migrations", "generated",
}
EXCLUDED_SUFFIXES = {".min.js", ".min.css", ".lock", ".map", ".pb.go", "_pb2.py"}
EXCLUDED_NAMES = {"package-lock.json", "yarn.lock", "poetry.lock", "Pipfile.lock"}
LANGUAGE_SUFFIXES = {"python": {".py"}}
GENERATED_MARKERS = ("@generated", "code generated", "auto-generated", "autogenerated", "do not edit")


def _is_generated(path: Path) -> bool:
    try:
        header = path.read_text(encoding="utf-8", errors="ignore")[:2048].casefold()
    except OSError:
        return True
    return any(marker in header for marker in GENERATED_MARKERS)


def filter_files(root: Path, language: str, is_fork: bool) -> tuple[list[str], list[str]]:
    """Returns (kept_paths, excluded_paths), both relative to root."""
    root = root.resolve()
    suffixes = LANGUAGE_SUFFIXES.get(language.casefold())
    if suffixes is None:
        raise ValueError(f"Unsupported target language: {language}")

    kept: list[str] = []
    excluded: list[str] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        parts = set(path.relative_to(root).parts)
        name = path.name

        try:
            resolved = path.resolve()
        except (OSError, RuntimeError):
            excluded.append(relative)
            continue

        exclude = (
            not resolved.is_relative_to(root)
            or bool(parts & EXCLUDED_DIRS)
            or name in EXCLUDED_NAMES
            or any(name.endswith(suffix) for suffix in EXCLUDED_SUFFIXES)
            or path.suffix.casefold() not in suffixes
            or _is_generated(path)
        )
        if exclude:
            excluded.append(relative)
        else:
            kept.append(relative)

    # Fork status is retained by the caller. Without an upstream ref, filtering
    # cannot safely distinguish an unchanged fork from original work, so it
    # conservatively keeps eligible source instead of discarding valid commits.
    _ = is_fork
    return kept, excluded
