"""End-to-end tests for deterministic RepoMap assembly."""

import os
from pathlib import Path
import subprocess

from app.config import Settings
from app.services import ingest


def _git(root: Path, *arguments: str, env: dict[str, str] | None = None) -> str:
    result = subprocess.run(
        ["git", "-C", str(root), *arguments],
        check=True,
        capture_output=True,
        text=True,
        env=env,
    )
    return result.stdout.strip()


def _repository(root: Path) -> str:
    files = {
        "app.py": (
            "def calculate(value):\n"
            "    if value > 0:\n"
            "        return value + 1\n"
            "    return 0\n"
        ),
        "tests/test_app.py": (
            "from app import calculate\n\n"
            "def test_calculate():\n"
            "    assert calculate(1) == 2\n"
        ),
        "generated.py": "# Code generated by a tool. DO NOT EDIT.\n",
        "README.md": "# Example\n",
    }
    for relative, content in files.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    _git(root, "init", "-q")
    _git(root, "add", "-A")
    commit_env = {
        **os.environ,
        "GIT_AUTHOR_NAME": "Developer",
        "GIT_AUTHOR_EMAIL": "developer@example.com",
        "GIT_COMMITTER_NAME": "Developer",
        "GIT_COMMITTER_EMAIL": "developer@example.com",
    }
    _git(root, "commit", "-q", "-m", "initial implementation", env=commit_env)
    return _git(root, "rev-parse", "HEAD")


def test_build_repo_map_runs_all_deterministic_stages(tmp_path: Path, monkeypatch):
    created_commit = _repository(tmp_path)
    clone_calls: list[tuple[str, str, str]] = []

    def fake_clone(settings, user, repo_full_name, token):
        clone_calls.append((user, repo_full_name, token))
        return tmp_path

    monkeypatch.setattr(ingest.clone_service, "clone", fake_clone)
    settings = Settings(cache_dir=tmp_path / "cache", target_language="python")

    repo_map = ingest.build_repo_map(
        settings,
        "developer",
        "developer/project",
        "github-token",
    )

    assert clone_calls == [("developer", "developer/project", "github-token")]
    assert repo_map.repo == "developer/project"
    assert repo_map.language == "python"
    assert repo_map.analyzed_at.tzinfo is not None
    assert repo_map.total_files == 2
    assert {"README.md", "generated.py"}.issubset(repo_map.excluded_files)

    functions = {function.qualified_name: function for function in repo_map.functions}
    calculate = functions["app.py::calculate"]
    assert calculate.complexity == 2
    assert calculate.nesting_depth == 1
    assert calculate.has_test is True
    assert calculate.times_modified == 1
    assert calculate.created_commit == created_commit
    assert calculate.last_modified is not None
    assert calculate.author_ratio == 1.0
    assert "tests/test_app.py::test_calculate" in functions


def test_build_repo_map_applies_optional_blame_with_supplied_email(tmp_path: Path, monkeypatch):
    _repository(tmp_path)
    monkeypatch.setattr(ingest.clone_service, "clone", lambda *args: tmp_path)
    calls: list[str] = []

    def fake_blame(root, functions, author_email):
        calls.append(author_email)
        for function in functions:
            function.author_ratio = 0.75
        return functions

    monkeypatch.setattr(ingest.blame_service, "enrich", fake_blame)
    settings = Settings(enable_blame=True)

    repo_map = ingest.build_repo_map(
        settings,
        "developer",
        "developer/project",
        "",
        is_fork=True,
        author_email="developer@example.com",
    )

    assert calls == ["developer@example.com"]
    assert all(function.author_ratio == 0.75 for function in repo_map.functions)


def test_build_repo_map_skips_blame_when_email_is_unavailable(tmp_path: Path, monkeypatch):
    _repository(tmp_path)
    monkeypatch.setattr(ingest.clone_service, "clone", lambda *args: tmp_path)

    def unexpected_blame(*args, **kwargs):
        raise AssertionError("blame should not run without an author email")

    monkeypatch.setattr(ingest.blame_service, "enrich", unexpected_blame)
    settings = Settings(enable_blame=True)

    repo_map = ingest.build_repo_map(settings, "developer", "developer/project", "")

    assert all(function.author_ratio == 1.0 for function in repo_map.functions)
