"""Phase 1 tests for cloning, filtering, and source slices."""

from pathlib import Path

import pytest
from fastapi import HTTPException

from app.config import Settings
from app.routers.code import _read_slice, _safe_path_from_root
from app.services.ingest import clone as clone_service
from app.services.ingest.filter import filter_files


def test_clone_uses_shallow_git_and_keeps_token_out_of_url(tmp_path: Path, monkeypatch):
    calls = []

    def fake_clone_from(url, destination, **kwargs):
        calls.append((url, Path(destination), kwargs))
        Path(destination).mkdir(parents=True)
        (Path(destination) / "main.py").write_text("print('ok')\n", encoding="utf-8")

    monkeypatch.setattr(clone_service.Repo, "clone_from", fake_clone_from)
    settings = Settings(cache_dir=tmp_path / "cache", clone_depth=25, max_repo_mb=1)

    destination = clone_service.clone(settings, "developer", "developer/project", "secret-token")

    assert destination == (tmp_path / "cache" / "developer" / "project").resolve()
    assert calls[0][0] == "https://github.com/developer/project.git"
    assert "secret-token" not in calls[0][0]
    assert calls[0][2]["depth"] == 25
    assert calls[0][2]["env"]["GIT_CONFIG_VALUE_0"].startswith("Authorization: Basic ")


def test_clone_cleans_partial_checkout_when_size_limit_is_exceeded(tmp_path: Path, monkeypatch):
    def fake_clone_from(url, destination, **kwargs):
        Path(destination).mkdir(parents=True)
        (Path(destination) / "large.bin").write_bytes(b"x" * 2048)

    monkeypatch.setattr(clone_service.Repo, "clone_from", fake_clone_from)
    settings = Settings(cache_dir=tmp_path / "cache", max_repo_mb=0)

    with pytest.raises(ValueError, match="clone limit"):
        clone_service.clone(settings, "developer", "developer/project", "")

    assert not (tmp_path / "cache" / "developer" / "project").exists()


@pytest.mark.parametrize("value", ["../user", "a/b", "", ".", ".."])
def test_clone_rejects_unsafe_cache_segments(tmp_path: Path, value: str):
    settings = Settings(cache_dir=tmp_path / "cache")

    with pytest.raises(ValueError):
        clone_service.cleanup(settings, value, "project")


def test_filter_returns_kept_and_explainable_exclusions(tmp_path: Path):
    files = {
        "app/main.py": "print('keep')\n",
        "app/generated.py": "# Code generated by a tool. DO NOT EDIT.\n",
        "tests/test_main.py": "def test_main(): pass\n",
        "node_modules/tool.py": "print('vendor')\n",
        "dist/bundle.py": "print('build')\n",
        "app/types_pb2.py": "# protobuf output\n",
        "README.md": "docs\n",
        "poetry.lock": "lock\n",
    }
    for relative, content in files.items():
        path = tmp_path / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    kept, excluded = filter_files(tmp_path, "python", is_fork=False)

    assert kept == ["app/main.py", "tests/test_main.py"]
    assert set(excluded) == set(files) - set(kept)


def test_filter_rejects_unsupported_languages(tmp_path: Path):
    with pytest.raises(ValueError, match="Unsupported"):
        filter_files(tmp_path, "rust", is_fork=False)


def test_source_slice_is_inclusive_and_rejects_invalid_ranges(tmp_path: Path):
    source = tmp_path / "app.py"
    source.write_text("one\ntwo\nthree\n", encoding="utf-8")

    assert _read_slice(source, 2, 3) == ["two", "three"]
    with pytest.raises(HTTPException) as reversed_range:
        _read_slice(source, 3, 2)
    assert reversed_range.value.status_code == 400
    with pytest.raises(HTTPException) as past_end:
        _read_slice(source, 1, 4)
    assert past_end.value.status_code == 416


def test_safe_source_path_rejects_traversal_and_symlink_escape(tmp_path: Path):
    root = tmp_path / "repo"
    root.mkdir()
    outside = tmp_path / "outside.py"
    outside.write_text("secret\n", encoding="utf-8")

    with pytest.raises(HTTPException) as traversal:
        _safe_path_from_root(root, "../outside.py")
    assert traversal.value.status_code == 400

    link = root / "linked.py"
    try:
        link.symlink_to(outside)
    except OSError as exc:
        pytest.skip(f"symlinks are unavailable: {exc}")
    with pytest.raises(HTTPException) as symlink:
        _safe_path_from_root(root, "linked.py")
    assert symlink.value.status_code == 400
