"""FastAPI entrypoint.

NOTE FOR THE TEAM: every router is already mounted below. Do not edit this file
on a feature branch -- it is the one file all four tracks would collide on.
Fill in your own router module instead.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.sessions import SessionMiddleware

from .config import get_settings
from .models.db import SessionLocal, init_db
from .routers import analysis, auth, code, community, drills, recall, repos, roadmap
from .services.storage import fail_interrupted_analyses

settings = get_settings()

app = FastAPI(
    title="Futura — code-evidenced capability profile",
    version="0.1.0",
    docs_url="/docs",
)

app.add_middleware(SessionMiddleware, secret_key=settings.session_secret)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(repos.router)
app.include_router(analysis.router)
app.include_router(recall.router)
app.include_router(drills.router)
app.include_router(roadmap.router)
app.include_router(code.router)
app.include_router(community.router)


@app.on_event("startup")
def _create_schema() -> None:
    """Ensure the tables exist before the first request touches them.

    init_db() used to run only from the OAuth callback and the repo sync, so a
    fresh database 500ed on any other endpoint until one of those happened to
    be hit first. It is idempotent, so running it here costs nothing.

    Analyses a previous process left half-done are closed here too. Nothing is
    running yet at this point, so any row that claims to be is an orphan.
    """
    init_db()
    if not settings.mock_mode:
        with SessionLocal() as db:
            fail_interrupted_analyses(db)


@app.get("/health", tags=["meta"])
def health() -> dict[str, str | bool]:
    return {"status": "ok", "mock_mode": settings.mock_mode}
