"""FastAPI entrypoint.

NOTE FOR THE TEAM: every router is already mounted below. Do not edit this file
on a feature branch -- it is the one file all four tracks would collide on.
Fill in your own router module instead.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.sessions import SessionMiddleware

from .config import get_settings
from .routers import analysis, auth, code, recall, repos, roadmap

settings = get_settings()

app = FastAPI(
    title="Futura — code-evidenced capability profile",
    version="0.1.0",
    docs_url="/docs",
)

app.add_middleware(SessionMiddleware, secret_key=settings.session_secret)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(repos.router)
app.include_router(analysis.router)
app.include_router(recall.router)
app.include_router(roadmap.router)
app.include_router(code.router)


@app.get("/health", tags=["meta"])
def health() -> dict[str, str | bool]:
    return {"status": "ok", "mock_mode": settings.mock_mode}
